version: 0.2

phases:
 install:
  runtime-versions:
   python: 3.11
  commands:
   - pip install --upgrade pip
   # Install dependencies needed for running the static analysis
   - pip install -r requirements.txt pylint
   
 pre_build:
  commands:
   - python --version
   - pylint $CODEBUILD_SRC_DIR/*.py
   - pylint $CODEBUILD_SRC_DIR/core/*.py
   - pylint --disable=E0401,R1735,R0903,R1725,R0901,E1101,W0107,R1710,W1309 $CODEBUILD_SRC_DIR/apps/bookings/*.py
   
artifacts:
  files:
   - '**/*'