# Generated by Django 4.2.7 on 2024-03-17 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.CharField(max_length=50)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("availability_status", models.BooleanField(default=True)),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("longitude", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
            },
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle images/"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_images",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Image",
                "verbose_name_plural": "Vehicle Images",
            },
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["type", "location"], name="vehicles_ve_type_7a418b_idx"
            ),
        ),
    ]
