# Generated by Django 4.2.7 on 2024-03-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="aircondition",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="temperature_regulator",
            field=models.CharField(
                choices=[
                    ("", "Select Temperature"),
                    ("Air Conditoning", "Air Conditoning"),
                    ("Climate Control", "Climate Control"),
                ],
                default="Air Conditioning",
                max_length=50,
            ),
        ),
    ]
