# Generated by Django 4.2.7 on 2024-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="make",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Make"),
                    ("TOYOTA", "Toyota"),
                    ("HONDA", "Honda"),
                    ("FORD", "Ford"),
                    ("CHEVROLET", "Chevrolet"),
                    ("BMW", "BMW"),
                    ("MERCEDES BENZ", "Mercedes Benz"),
                    ("AUDI", "Audi"),
                    ("NISSAN", "Nissan"),
                    ("VOLKSWAGEN", "Volkswagen"),
                    ("TESLA", "Tesla"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Type"),
                    ("SEDAN", "Sedan"),
                    ("SUV", "SUV"),
                    ("TRUCK", "Truck"),
                    ("HATCHBACK", "Hatchback"),
                    ("COUPE", "Coupe"),
                    ("CONVERTIBLE", "Convertible"),
                    ("MINIVAN", "Minivan"),
                    ("PICKUP", "Pickup"),
                    ("VAN", "Van"),
                    ("CROSSOVER", "Crossover"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
