# Generated by Django 4.2.7 on 2024-03-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_vehicle_make_alter_vehicle_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="longitude",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="vehicle images/"),
        ),
        migrations.DeleteModel(
            name="VehicleImage",
        ),
    ]
