# Generated by Django 4.2.7 on 2024-03-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_alter_vehicle_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="registration_number",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="registration_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="vehicle certificates/"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("Gasoline", "Gasoline"),
                    ("Petrol", "Petrol"),
                    ("Diesel", "Diesel"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="temperature_regulator",
            field=models.CharField(
                choices=[
                    ("", "Select"),
                    ("Air Conditoning", "Air Conditoning"),
                    ("Climate Control", "Climate Control"),
                ],
                default="Air Conditioning",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="total_doors",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="total_passengers",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("10", "10"),
                    ("15", "15"),
                    ("24", "24"),
                    ("40", "40"),
                    ("50", "50"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="transmission_type",
            field=models.CharField(
                blank=True,
                choices=[("", "Select"), ("Manual", "Manual"), ("Auto", "Auto")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_make",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("Toyota", "Toyota"),
                    ("Honda", "Honda"),
                    ("Ford", "Ford"),
                    ("Chevrolet", "Chevrolet"),
                    ("Bmw", "Bmw"),
                    ("Mercedes Benz", "Mercedes Benz"),
                    ("Audi", "Audi"),
                    ("Nissan", "Nissan"),
                    ("Volkswagen", "Volkswagen"),
                    ("Tesla", "Tesla"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select"),
                    ("Sedan", "Sedan"),
                    ("Suv", "Suv"),
                    ("Truck", "Truck"),
                    ("Hatchback", "Hatchback"),
                    ("Coupe", "Coupe"),
                    ("Convertible", "Convertible"),
                    ("Mini Van", "Mini Van"),
                    ("Pickup", "Pickup"),
                    ("Van", "Van"),
                    ("Crossover", "Crossover"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
