# Generated by Django 4.2.7 on 2024-03-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="personal_description",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
