# Generated by Django 4.2.7 on 2024-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_personal_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="images/dummy.png", upload_to="profile picture/"
            ),
        ),
    ]
