# Generated by Django 4.2.7 on 2024-03-18 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateTimeField(verbose_name=datetime.datetime),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateTimeField(verbose_name=datetime.datetime),
        ),
    ]
