# Generated by Django 4.2.7 on 2024-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_end_date_alter_booking_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_hours",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
