# Generated by Django 4.2.7 on 2024-03-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_alter_vehicle_owner"),
        ("bookings", "0003_booking_address_booking_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="vehicles.vehicle",
            ),
        ),
    ]
