# Generated by Django 4.2.7 on 2024-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_booking_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="approval",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Declined", "Declined"),
                ],
                default="Approved",
                max_length=100,
            ),
        ),
    ]
