# Generated by Django 4.2.7 on 2024-04-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_booking_approval"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="approval",
            new_name="status",
        ),
    ]
