# Generated by Django 4.2.7 on 2024-04-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_rename_approval_booking_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="state",
            new_name="county",
        ),
    ]
